goldfish: fix -Wmissing-prototypes errors
Add missing 'static' keyword to several functions. This resolves build
issues after enabling -Wmissing-prototypes such as the following:

  common-modules/virtual-device/goldfish_drivers/goldfish_sync.c:189:2: error: no previous prototype for function 'goldfish_sync_timeline_create' [-Werror,-Wmissing-prototypes]
    189 | *goldfish_sync_timeline_create(struct goldfish_sync_state *sync_state)
        |  ^

Cc: Alistair Delva <adelva@google.com>
Fixes: 6c990a1 ("Initial code for the common-modules/virtual-devices project")
Change-Id: I97bc4cfea69e761f1f83153614d344949f2003af
Signed-off-by: Carlos Llamas <cmllamas@google.com>