kleaf: fix -Wmissing-prototypes errors
Add missing prototypes and tag several functions as 'static' to fix
mulitple -Wmissing-prototypes issues such as:

  common-modules/virtual-device/kleaf_test/assembly_test/empty_module.c:24:6: error: no previous prototype for function 'bar' [-Werror,-Wmissing-prototypes]
     24 | void bar(void) {
        |      ^

Change-Id: Ifdab9a997276cb15f55492714711bd4bc00c6da9
Signed-off-by: Carlos Llamas <cmllamas@google.com>